# Generated by Django 3.2.4 on 2022-09-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncity', models.CharField(max_length=30)),
                ('cdate', models.DateField()),
            ],
        ),
    ]
