# Generated by Django 3.2.4 on 2022-09-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='mambers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('cacc', models.CharField(max_length=26)),
                ('caddress', models.TextField()),
                ('paddress', models.TextField()),
                ('pcode', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
