# Generated by Django 3.2.4 on 2022-09-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_mambers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mambers',
            new_name='members',
        ),
    ]
