# Generated by Django 3.2.4 on 2022-09-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_mambers_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='ppic',
            field=models.ImageField(null=True, upload_to='static/profile/'),
        ),
    ]
