# Generated by Django 3.2.4 on 2022-09-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_members_ppic'),
    ]

    operations = [
        migrations.CreateModel(
            name='vgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlink', models.TextField()),
                ('vdes', models.TextField()),
                ('vtitle', models.CharField(max_length=200)),
                ('vdate', models.DateField()),
            ],
        ),
    ]
