# Generated by Django 3.2.4 on 2022-09-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_vgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avalue', models.IntegerField()),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('mob', models.CharField(max_length=50)),
                ('cont', models.CharField(max_length=40)),
                ('add', models.CharField(max_length=100)),
                ('sta', models.CharField(max_length=40)),
                ('pin', models.IntegerField()),
                ('occ', models.CharField(max_length=20)),
                ('ppic', models.ImageField(null=True, upload_to='static/profile')),
            ],
        ),
    ]
