# Generated by Django 3.2.4 on 2022-09-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_donate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donate',
            new_name='donateus',
        ),
    ]
