# Generated by Django 3.2.4 on 2022-09-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_donateus_avalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateus',
            name='avalue',
            field=models.IntegerField(max_length=5),
        ),
    ]
