# Generated by Django 3.2.4 on 2022-09-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_donateus_ppic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateus',
            name='ppic',
            field=models.ImageField(null=True, upload_to='static/profile/'),
        ),
    ]
