# Generated by Django 3.2.4 on 2022-09-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_donateus_ppic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='donateus',
        ),
    ]
