# Generated by Django 3.2.4 on 2022-09-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_donateus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateus',
            name='ppic',
            field=models.ImageField(upload_to='static/screenshot/'),
        ),
    ]
